INSERT INTO state (initials, name) VALUES ("AC", "Acre");
INSERT INTO state (initials, name) VALUES ("AL", "Alagoas");
INSERT INTO state (initials, name) VALUES ("AP", "Amapá");
INSERT INTO state (initials, name) VALUES ("AM", "Amazonas");
INSERT INTO state (initials, name) VALUES ("BA", "Bahia");
INSERT INTO state (initials, name) VALUES ("CE", "Ceará");
INSERT INTO state (initials, name) VALUES ("DF", "Distrito Federal");
INSERT INTO state (initials, name) VALUES ("ES", "Espírito Santo");
INSERT INTO state (initials, name) VALUES ("GO", "Goiás");
INSERT INTO state (initials, name) VALUES ("MA", "Maranhão");
INSERT INTO state (initials, name) VALUES ("MT", "Mato Grosso");
INSERT INTO state (initials, name) VALUES ("MS", "Mato Grosso do Sul");
INSERT INTO state (initials, name) VALUES ("MG", "Minhas Gerais");
INSERT INTO state (initials, name) VALUES ("PA", "Pará");
INSERT INTO state (initials, name) VALUES ("PB", "Paraíba");
INSERT INTO state (initials, name) VALUES ("PN", "Paraná");
INSERT INTO state (initials, name) VALUES ("PE", "Pernambuco");
INSERT INTO state (initials, name) VALUES ("PI", "Piauí");
INSERT INTO state (initials, name) VALUES ("RJ", "Rio de Janeiro");
INSERT INTO state (initials, name) VALUES ("RN", "Rio Grande do Norte");
INSERT INTO state (initials, name) VALUES ("RS", "Rio Grande do Sul");
INSERT INTO state (initials, name) VALUES ("RO", "Rondônia");
INSERT INTO state (initials, name) VALUES ("RR", "Rorâima");
INSERT INTO state (initials, name) VALUES ("SC", "Santa Catarina");
INSERT INTO state (initials, name) VALUES ("SP", "São Paulo");
INSERT INTO state (initials, name) VALUES ("SE", "Sergipe");
INSERT INTO state (initials, name) VALUES ("TO", "Tocantins");
