INSERT INTO country (name) VALUES ("Afeganistão");
INSERT INTO country (name) VALUES ("África do Sul");
INSERT INTO country (name) VALUES ("Albânia");
INSERT INTO country (name) VALUES ("Alemanha");
INSERT INTO country (name) VALUES ("Andorra");
INSERT INTO country (name) VALUES ("Angola");
INSERT INTO country (name) VALUES ("Antiga e Barbuda");
INSERT INTO country (name) VALUES ("Arábia Saudita");
INSERT INTO country (name) VALUES ("Argélia");
INSERT INTO country (name) VALUES ("Argentina");
INSERT INTO country (name) VALUES ("Arménia");
INSERT INTO country (name) VALUES ("Austrália");
INSERT INTO country (name) VALUES ("Áustria");
INSERT INTO country (name) VALUES ("Azerbaijão");
INSERT INTO country (name) VALUES ("Bahamas");
INSERT INTO country (name) VALUES ("Bangladexe");
INSERT INTO country (name) VALUES ("Barbados");
INSERT INTO country (name) VALUES ("Barém");
INSERT INTO country (name) VALUES ("Bélgica");
INSERT INTO country (name) VALUES ("Belize");
INSERT INTO country (name) VALUES ("Benim");
INSERT INTO country (name) VALUES ("Bielorrússia");
INSERT INTO country (name) VALUES ("Bolívia");
INSERT INTO country (name) VALUES ("Bósnia e Herzegovina");
INSERT INTO country (name) VALUES ("Botsuana");
INSERT INTO country (name) VALUES ("Brasil");
INSERT INTO country (name) VALUES ("Brunei");
INSERT INTO country (name) VALUES ("Bulgária");
INSERT INTO country (name) VALUES ("Burquina Faso");
INSERT INTO country (name) VALUES ("Burúndi");
INSERT INTO country (name) VALUES ("Butão");
INSERT INTO country (name) VALUES ("Cabo Verde");
INSERT INTO country (name) VALUES ("Camarões");
INSERT INTO country (name) VALUES ("Camboja");
INSERT INTO country (name) VALUES ("Canadá");
INSERT INTO country (name) VALUES ("Catar");
INSERT INTO country (name) VALUES ("Cazaquistão");
INSERT INTO country (name) VALUES ("Chade");
INSERT INTO country (name) VALUES ("Chile");
INSERT INTO country (name) VALUES ("China");
INSERT INTO country (name) VALUES ("Chipre");
INSERT INTO country (name) VALUES ("Colômbia");
INSERT INTO country (name) VALUES ("Comores");
INSERT INTO country (name) VALUES ("Congo-Brazzaville");
INSERT INTO country (name) VALUES ("Coreia do Norte");
INSERT INTO country (name) VALUES ("Coreia do Sul");
INSERT INTO country (name) VALUES ("Cosovo");
INSERT INTO country (name) VALUES ("Costa do Marfim");
INSERT INTO country (name) VALUES ("Costa Rica");
INSERT INTO country (name) VALUES ("Croácia");
INSERT INTO country (name) VALUES ("Cuaite");
INSERT INTO country (name) VALUES ("Cuba");
INSERT INTO country (name) VALUES ("Dinamarca");
INSERT INTO country (name) VALUES ("Dominica");
INSERT INTO country (name) VALUES ("Egito");
INSERT INTO country (name) VALUES ("Emirados Árabes Unidos");
INSERT INTO country (name) VALUES ("Equador");
INSERT INTO country (name) VALUES ("Eritreia");
INSERT INTO country (name) VALUES ("Eslováquia");
INSERT INTO country (name) VALUES ("Eslovénia");
INSERT INTO country (name) VALUES ("Espanha");
INSERT INTO country (name) VALUES ("Estado da Palestina");
INSERT INTO country (name) VALUES ("Estados Unidos");
INSERT INTO country (name) VALUES ("Estónia");
INSERT INTO country (name) VALUES ("Etiópia");
INSERT INTO country (name) VALUES ("Fiji");
INSERT INTO country (name) VALUES ("Filipinas");
INSERT INTO country (name) VALUES ("Finlândia");
INSERT INTO country (name) VALUES ("França");
INSERT INTO country (name) VALUES ("Gabão");
INSERT INTO country (name) VALUES ("Gâmbia");
INSERT INTO country (name) VALUES ("Gana");
INSERT INTO country (name) VALUES ("Geórgia");
INSERT INTO country (name) VALUES ("Granada");
INSERT INTO country (name) VALUES ("Grécia");
INSERT INTO country (name) VALUES ("Guatemala");
INSERT INTO country (name) VALUES ("Guiana");
INSERT INTO country (name) VALUES ("Guiné");
INSERT INTO country (name) VALUES ("Guiné Equatorial");
INSERT INTO country (name) VALUES ("Guiné-Bissau");
INSERT INTO country (name) VALUES ("Haiti");
INSERT INTO country (name) VALUES ("Honduras");
INSERT INTO country (name) VALUES ("Hungria");
INSERT INTO country (name) VALUES ("Iémen");
INSERT INTO country (name) VALUES ("Ilhas Marechal");
INSERT INTO country (name) VALUES ("Índia");
INSERT INTO country (name) VALUES ("Indonésia");
INSERT INTO country (name) VALUES ("Irão");
INSERT INTO country (name) VALUES ("Iraque");
INSERT INTO country (name) VALUES ("Irlanda");
INSERT INTO country (name) VALUES ("Islândia");
INSERT INTO country (name) VALUES ("Israel");
INSERT INTO country (name) VALUES ("Itália");
INSERT INTO country (name) VALUES ("Jamaica");
INSERT INTO country (name) VALUES ("Japão");
INSERT INTO country (name) VALUES ("Jibuti");
INSERT INTO country (name) VALUES ("Jordânia");
INSERT INTO country (name) VALUES ("Laus");
INSERT INTO country (name) VALUES ("Lesoto");
INSERT INTO country (name) VALUES ("Letónia");
INSERT INTO country (name) VALUES ("Líbano");
INSERT INTO country (name) VALUES ("Libéria");
INSERT INTO country (name) VALUES ("Líbia");
INSERT INTO country (name) VALUES ("Listenstaine");
INSERT INTO country (name) VALUES ("Lituânia");
INSERT INTO country (name) VALUES ("Luxemburgo");
INSERT INTO country (name) VALUES ("Macedónia");
INSERT INTO country (name) VALUES ("Madagáscar");
INSERT INTO country (name) VALUES ("Malásia");
INSERT INTO country (name) VALUES ("Maláui");
INSERT INTO country (name) VALUES ("Maldivas");
INSERT INTO country (name) VALUES ("Mali");
INSERT INTO country (name) VALUES ("Malta");
INSERT INTO country (name) VALUES ("Marrocos");
INSERT INTO country (name) VALUES ("Maurícia");
INSERT INTO country (name) VALUES ("Mauritânia");
INSERT INTO country (name) VALUES ("México");
INSERT INTO country (name) VALUES ("Mianmar");
INSERT INTO country (name) VALUES ("Micronésia");
INSERT INTO country (name) VALUES ("Moçambique");
INSERT INTO country (name) VALUES ("Moldávia");
INSERT INTO country (name) VALUES ("Mónaco");
INSERT INTO country (name) VALUES ("Mongólia");
INSERT INTO country (name) VALUES ("Montenegro");
INSERT INTO country (name) VALUES ("Namíbia");
INSERT INTO country (name) VALUES ("Nauru");
INSERT INTO country (name) VALUES ("Nepal");
INSERT INTO country (name) VALUES ("Nicarágua");
INSERT INTO country (name) VALUES ("Níger");
INSERT INTO country (name) VALUES ("Nigéria");
INSERT INTO country (name) VALUES ("Noruega");
INSERT INTO country (name) VALUES ("Nova Zelândia");
INSERT INTO country (name) VALUES ("Omã");
INSERT INTO country (name) VALUES ("Países Baixos");
INSERT INTO country (name) VALUES ("Palau");
INSERT INTO country (name) VALUES ("Panamá");
INSERT INTO country (name) VALUES ("Papua Nova Guiné");
INSERT INTO country (name) VALUES ("Paquistão");
INSERT INTO country (name) VALUES ("Paraguai");
INSERT INTO country (name) VALUES ("Peru");
INSERT INTO country (name) VALUES ("Polónia");
INSERT INTO country (name) VALUES ("Portugal");
INSERT INTO country (name) VALUES ("Quénia");
INSERT INTO country (name) VALUES ("Quirguistão");
INSERT INTO country (name) VALUES ("Quiribáti");
INSERT INTO country (name) VALUES ("Reino Unido");
INSERT INTO country (name) VALUES ("República Centro-Africana");
INSERT INTO country (name) VALUES ("República Checa");
INSERT INTO country (name) VALUES ("República Democrática do Congo");
INSERT INTO country (name) VALUES ("República Dominicana");
INSERT INTO country (name) VALUES ("Roménia");
INSERT INTO country (name) VALUES ("Ruanda");
INSERT INTO country (name) VALUES ("Rússia");
INSERT INTO country (name) VALUES ("Salomão");
INSERT INTO country (name) VALUES ("Salvador");
INSERT INTO country (name) VALUES ("Samoa");
INSERT INTO country (name) VALUES ("Santa Lúcia");
INSERT INTO country (name) VALUES ("São Cristóvão e Neves");
INSERT INTO country (name) VALUES ("São Marinho");
INSERT INTO country (name) VALUES ("São Tomé e Príncipe");
INSERT INTO country (name) VALUES ("São Vicente e Granadinas");
INSERT INTO country (name) VALUES ("Seicheles");
INSERT INTO country (name) VALUES ("Senegal");
INSERT INTO country (name) VALUES ("Serra Leoa");
INSERT INTO country (name) VALUES ("Sérvia");
INSERT INTO country (name) VALUES ("Singapura");
INSERT INTO country (name) VALUES ("Síria");
INSERT INTO country (name) VALUES ("Somália");
INSERT INTO country (name) VALUES ("Sri Lanca");
INSERT INTO country (name) VALUES ("Suazilândia");
INSERT INTO country (name) VALUES ("Sudão");
INSERT INTO country (name) VALUES ("Sudão do Sul");
INSERT INTO country (name) VALUES ("Suécia");
INSERT INTO country (name) VALUES ("Suíça");
INSERT INTO country (name) VALUES ("Suriname");
INSERT INTO country (name) VALUES ("Tailândia");
INSERT INTO country (name) VALUES ("Taiuã");
INSERT INTO country (name) VALUES ("Tajiquistão");
INSERT INTO country (name) VALUES ("Tanzânia");
INSERT INTO country (name) VALUES ("Timor-Leste");
INSERT INTO country (name) VALUES ("Togo");
INSERT INTO country (name) VALUES ("Tonga");
INSERT INTO country (name) VALUES ("Trindade e Tobago");
INSERT INTO country (name) VALUES ("Tunísia");
INSERT INTO country (name) VALUES ("Turcomenistão");
INSERT INTO country (name) VALUES ("Turquia");
INSERT INTO country (name) VALUES ("Tuvalu");
INSERT INTO country (name) VALUES ("Ucrânia");
INSERT INTO country (name) VALUES ("Uganda");
INSERT INTO country (name) VALUES ("Uruguai");
INSERT INTO country (name) VALUES ("Usbequistão");
INSERT INTO country (name) VALUES ("Vanuatu");
INSERT INTO country (name) VALUES ("Vaticano");
INSERT INTO country (name) VALUES ("Venezuela");
INSERT INTO country (name) VALUES ("Vietname");
INSERT INTO country (name) VALUES ("Zâmbia");
INSERT INTO country (name) VALUES ("Zimbábue");
